name: macOS

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-13, macos-14]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Homebrew packages
      run: |
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        brew update
        brew install ffmpeg meson vapoursynth xxhash

    - name: Build
      run: |
        CFLAGS="-Wall -Wextra -Wpedantic" CXXFLAGS="-Wall -Wextra -Wpedantic" meson setup build
        ninja -C build
